# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import elections.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(editable=False, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=50)),
                ('desc', models.CharField(max_length=200)),
            ],
            bases=(models.Model, elections.models.ElectoralUnit),
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('votes_invalid', models.IntegerField()),
                ('votes_cast', models.IntegerField()),
                ('votes_valid', models.IntegerField()),
                ('entitled_to_vote', models.IntegerField()),
                ('ballots_issued', models.IntegerField()),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Circuit')),
            ],
            bases=(models.Model, elections.models.ElectoralUnit),
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            bases=(models.Model, elections.models.ElectoralUnit),
        ),
        migrations.CreateModel(
            name='ResultsInCommunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField()),
                ('candidate', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='elections.Candidate')),
                ('community', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='elections.Community')),
            ],
        ),
        migrations.AddField(
            model_name='circuit',
            name='province',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='elections.Province'),
        ),
    ]
