# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circuit',
            old_name='province',
            new_name='ancestor',
        ),
        migrations.RenameField(
            model_name='community',
            old_name='circuit',
            new_name='ancestor',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='first_name',
            field=models.CharField(editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='circuit',
            name='desc',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='circuit',
            name='name',
            field=models.CharField(editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
