# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import elections.models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_auto_20170426_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            bases=(models.Model, elections.models.ElectoralUnit),
        ),
    ]
